import { useCallback } from "react";
import { Itinerary } from "../types/trip";
import { getWeatherIcon } from "./useWeather";

export function usePDF() {
  const downloadPDF = useCallback(
    async (
      itinerary: Itinerary,
      interests: string[],
      weatherDays?: { maxTemp: number; minTemp: number; weatherCode: number }[],
    ) => {
      const { default: jsPDF } = await import("jspdf");

      const doc = new jsPDF({
        orientation: "portrait",
        unit: "mm",
        format: "a4",
      });

      const W = 210;
      const margin = 20;
      const contentW = W - margin * 2;
      let y = 0;

      // Renkler
      const indigo = [99, 102, 241] as const;
      const gray800 = [30, 30, 30] as const;
      const gray500 = [100, 100, 100] as const;
      const gray100 = [245, 245, 250] as const;
      const white = [255, 255, 255] as const;

      // Header arka planı
      doc.setFillColor(...indigo);
      doc.rect(0, 0, W, 45, "F");

      // Başlık
      doc.setTextColor(...white);
      doc.setFontSize(22);
      doc.setFont("helvetica", "bold");
      doc.text(`${itinerary.city}`, margin, 18);

      doc.setFontSize(12);
      doc.setFont("helvetica", "normal");
      doc.text(`${itinerary.days.length}-Day Itinerary`, margin, 27);

      // Interests
      doc.setFontSize(9);
      doc.setTextColor(200, 200, 255);
      doc.text(`Interests: ${interests.join(", ")}`, margin, 36);

      y = 55;

      // Hava durumu şeridi
      if (weatherDays?.length) {
        doc.setFillColor(...gray100);
        doc.roundedRect(margin, y, contentW, 22, 3, 3, "F");

        doc.setFontSize(8);
        doc.setTextColor(...gray500);
        doc.text("Weather forecast", margin + 4, y + 7);

        const slotW = contentW / Math.min(weatherDays.length, 7);
        weatherDays.slice(0, 7).forEach((day, idx) => {
          const x = margin + idx * slotW + slotW / 2;
          doc.setFontSize(9);
          doc.setTextColor(...gray800);
          doc.text(
            `${getWeatherIcon(day.weatherCode)} ${day.maxTemp}°`,
            x,
            y + 15,
            { align: "center" },
          );
        });

        y += 32;
      }

      // Günler
      for (const day of itinerary.days) {
        // Sayfa kontrolü
        if (y > 250) {
          doc.addPage();
          y = 20;
        }

        // Gün başlığı
        doc.setFillColor(...indigo);
        doc.roundedRect(margin, y, contentW, 10, 2, 2, "F");
        doc.setTextColor(...white);
        doc.setFontSize(11);
        doc.setFont("helvetica", "bold");
        doc.text(`Day ${day.day}`, margin + 4, y + 7);
        y += 16;

        const slots = [
          { label: "Morning", icon: "☀", data: day.morning },
          { label: "Afternoon", icon: "⛅", data: day.afternoon },
          { label: "Evening", icon: "🌙", data: day.evening },
        ];

        for (const slot of slots) {
          if (y > 265) {
            doc.addPage();
            y = 20;
          }

          // Kart arka planı
          doc.setFillColor(...gray100);
          doc.roundedRect(margin, y, contentW, 18, 2, 2, "F");

          // Sol renkli çizgi
          doc.setFillColor(...indigo);
          doc.rect(margin, y, 2, 18, "F");

          // Label
          doc.setTextColor(...gray500);
          doc.setFontSize(8);
          doc.setFont("helvetica", "normal");
          doc.text(slot.label, margin + 6, y + 6);

          // Activity
          doc.setTextColor(...gray800);
          doc.setFontSize(10);
          doc.setFont("helvetica", "bold");
          doc.text(slot.data.activity, margin + 6, y + 13);

          // Location
          doc.setTextColor(...indigo);
          doc.setFontSize(8);
          doc.setFont("helvetica", "normal");
          doc.text(`📍 ${slot.data.location}`, margin + 100, y + 13);

          y += 22;
        }

        y += 6;
      }

      // Footer
      doc.setFillColor(...gray100);
      doc.rect(0, 285, W, 12, "F");
      doc.setTextColor(...gray500);
      doc.setFontSize(8);
      doc.text("Generated by AI Travel Planner", margin, 293);
      doc.text(new Date().toLocaleDateString("en"), W - margin, 293, {
        align: "right",
      });

      doc.save(
        `${itinerary.city.toLowerCase().replace(/\s+/g, "-")}-itinerary.pdf`,
      );
    },
    [],
  );

  return { downloadPDF };
}
